wellnet_test_homepage:
    pattern:  /
    defaults: { _controller: WellnetTestBundle:Default:index, page: index }

wellnet_test_2legged:
    pattern:  /twolegged
    defaults: { _controller: WellnetTestBundle:Default:index, page: twolegged }

wellnet_test_3legged:
    pattern:  /threelegged
    defaults: { _controller: WellnetTestBundle:Default:threelegged }

wellnet_test_collaudo:
    pattern:  /collaudo
    defaults: { _controller: WellnetTestBundle:Default:index, page: collaudo }

wellnet_test_help_ita:
    pattern:  /help_ita
    defaults: { _controller: WellnetTestBundle:Default:index, page: helpIta }

wellnet_test_help_eng:
    pattern:  /help_eng
    defaults: { _controller: WellnetTestBundle:Default:index, page: helpEng }

wellnet_test_3legged_callback:
    pattern:  /threelegged/callback
    defaults: { _controller: WellnetTestBundle:ThreeLegged:service }

wellnet_test_3legged_destroy:
    pattern:  /threelegged/destroy
    defaults: { _controller: WellnetTestBundle:ThreeLegged:destroy }

# structure

wellnet_test_get_structure:
    pattern:  /structure/node/{type}
    defaults: { _controller: WellnetTestBundle:Structure:getStructure }

wellnet_test_change_state:
    pattern:  /structure/change_state/{nid}/{state}
    defaults: { _controller: WellnetTestBundle:Structure:changeState }

wellnet_test_unpublish_live:
    pattern:  /structure/unpublish_live/{nid}/{vid}/{state}
    defaults: { _controller: WellnetTestBundle:Structure:unpublishLive }

# nodes

wellnet_test_list_nodes:
    pattern:  /node/detail/{type}
    defaults: { _controller: WellnetTestBundle:Node:index }

wellnet_test_list_all_nodes:
    pattern:  /node_all
    defaults: { _controller: WellnetTestBundle:Node:allNodes }

wellnet_test_get_node:
    pattern:  /node/get/{nid}
    defaults: { _controller: WellnetTestBundle:Node:get }

wellnet_test_delete_node:
    pattern:  /node/delete/{nid}
    defaults: { _controller: WellnetTestBundle:Node:delete }

# accreditation

wellnet_test_create_accreditation_node:
    pattern:  /node/create_accreditation
    defaults: { _controller: WellnetTestBundle:AccreditationNode:create }

# eliot

wellnet_test_create_eliot_node:
    pattern:  /node/create_eliot
    defaults: { _controller: WellnetTestBundle:EliotNode:create }

wellnet_test_contributions_get_eliot_types:
    pattern: /eliot/get_types
    defaults: { _controller: WellnetTestBundle:EliotNode:getTypes }

# files

wellnet_test_create_file:
    pattern:  /file/create
    defaults: { _controller: WellnetTestBundle:File:create }

# topic

wellnet_test_list_nodes_topic:
    pattern:  /node/detail/topic
    defaults: { _controller: WellnetTestBundle:TopicNode:index }

wellnet_test_create_topic_node:
    pattern:  /node/create_topic
    defaults: { _controller: WellnetTestBundle:TopicNode:create }

wellnet_test_create_topic_tag:
    pattern:  /node/create_topic_tag/{name}
    defaults: { _controller: WellnetTestBundle:TopicNode:createTag }

# event

wellnet_test_create_event_node:
    pattern:  /node/create_event
    defaults: { _controller: WellnetTestBundle:EventNode:create }

wellnet_test_update_event_node:
    pattern:  /node/update_event/{nid}
    defaults: { _controller: WellnetTestBundle:EventNode:update }

wellnet_test_delete_event_node:
    pattern:  /node/delete_event/{nid}
    defaults: { _controller: WellnetTestBundle:EventNode:delete }

# poi

wellnet_test_create_poi_node:
    pattern:  /node/create_poi
    defaults: { _controller: WellnetTestBundle:PoiNode:create }

wellnet_test_update_poi_node:
    pattern:  /node/update_poi/{nid}
    defaults: { _controller: WellnetTestBundle:PoiNode:update }

# image

wellnet_test_create_image_node:
    pattern:  /node/create_image
    defaults: { _controller: WellnetTestBundle:ImageNode:create }

wellnet_test_update_image_node:
    pattern:  /node/update_image/{nid}
    defaults: { _controller: WellnetTestBundle:ImageNode:update }

# users

wellnet_test_list_users:
    pattern:  /user
    defaults: { _controller: WellnetTestBundle:User:index }

wellnet_test_get_user:
    pattern:  /user/get/{uid}
    defaults: { _controller: WellnetTestBundle:User:get }

wellnet_test_get_user_accreditation:
    pattern:  /user/get_accreditation/{id}
    defaults: { _controller: WellnetTestBundle:User:getAccreditation }

# groups

wellnet_test_get_group_members:
    pattern:  /group/get_members/{gid}
    defaults: { _controller: WellnetTestBundle:Group:getMembers }

wellnet_test_get_group_services:
    pattern:  /group/get_services/{gid}
    defaults: { _controller: WellnetTestBundle:Group:getServices }

# comments

wellnet_test_list_comments:
    pattern:  /comments/{nid}
    defaults: { _controller: WellnetTestBundle:Comment:index }

wellnet_test_create_comments:
    pattern:  /comments/create/{nid}
    defaults: { _controller: WellnetTestBundle:Comment:create }

wellnet_test_get_comments:
    pattern:  /comments/get/{cid}
    defaults: { _controller: WellnetTestBundle:Comment:get }

# workshops

wellnet_test_get_workshop_attendees:
    pattern:  /workshop/get_attendees/{nid}
    defaults: { _controller: WellnetTestBundle:Workshop:getAttendees }

wellnet_test_create_attendee_node:
    pattern:  /workshop/create_attendee
    defaults: { _controller: WellnetTestBundle:Workshop:createAttendee }

# contributions

wellnet_test_contributions_publish:
    pattern:  /contributions/publish/{nid}
    defaults: { _controller: WellnetTestBundle:Contribution:publish }

wellnet_test_contributions_get_themes:
    pattern:  /contributions/get_themes
    defaults: { _controller: WellnetTestBundle:Contribution:getThemes }

wellnet_test_contributions_grant_points:
    pattern:  /contributions/grant_points/{nid}
    defaults: { _controller: WellnetTestBundle:Contribution:grantPoints }

wellnet_test_contributions_remove_points:
    pattern:  /contributions/remove_points/{nid}
    defaults: { _controller: WellnetTestBundle:Contribution:removePoints }

wellnet_test_contributions_list_medias:
    pattern:  /contributions/list_medias
    defaults: { _controller: WellnetTestBundle:Contribution:listMedias }

wellnet_test_contributions_get_media:
    pattern:  /contributions/get_media/{nid}
    defaults: { _controller: WellnetTestBundle:Contribution:getMedia }

wellnet_test_contributions_get_media_file:
    pattern:  /contributions/get_media_file/{fid}
    defaults: { _controller: WellnetTestBundle:Contribution:getMediaFile }

wellnet_test_contributions_get_related:
    pattern:  /contributions/get_related/{nid}
    defaults: { _controller: WellnetTestBundle:Contribution:getRelated }

# webform

wellnet_test_list_webform:
  pattern:  /webform
  defaults: { _controller: WellnetTestBundle:Webform:indexWebform}

wellnet_test_get_webform:
  pattern:  /webform/get/{nid}
  defaults: { _controller: WellnetTestBundle:Webform:getWebform}

wellnet_test_webform_submission:
  pattern:  /submission/{nid}
  defaults: { _controller: WellnetTestBundle:Webform:getSubmission}
