parameters:
#    wellnet_test.example.class: Wellnet\Bundle\TestBundle\Example

services:
#    wellnet_test.example:
#        class: %wellnet_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
