parameters:

# symfony parameters
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: symfony
  database_user: root
  database_password: null
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: ThisTokenIsNotSoSecretChangeIt

# rest client parameters
  server_url: http://ao
  consumer_key: QyfHxEZsQm96nXbT32Q3QN95jahBtqvC
  consumer_secret: R9v7GQMHTKNoAUvS5txinymZKCau7uki
  consumer_key_3legged: esubmPgd5bjauzEwUSnzHxbTHgueHR8C
  consumer_secret_3legged: FKUznD4wcFEXUb5PY7CAVnbfx62g4ycc
  request_token_uri: http://ao/oauth/request_token
  authorize_uri: http://ao/oauth/authorize
  access_token_uri: http://ao/oauth/access_token
  resource_uri: http://ao/en/api_3_legs/1.0/node
  username: sardegnait
  password: 111111

